{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1725479841258,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #29948","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/29948/","buildNumber":29948,"builtOn":"test-rackspace-win2022_vs2022-x64-6","nodeVersion":"23.0.0","commitHash":"26610546771c67ea3c0427bd8df7e394da2960d0","callStack":[{"upstreamBuild":65512,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":73936,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":61933,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54651"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":108,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (4435.6401ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (4425.0131ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (4707.4118ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (5094.4477ms)\n  ✖ async-hooks\\test-async-local-storage-enable-disable.js (4932.6085ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enable-disable.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 4)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (4887.1112ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (5140.5015ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (4674.5811ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (5149.1716ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (5233.1761ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (4508.0602ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (5095.7432ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (5031.6992ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (5438.359ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (4889.9902ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (4575.1569ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (4964.1706ms)\n  ✔ parallel\\test-async-local-storage-bind.js (4854.3714ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (4273.377ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (5310.0949ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (4946.5183ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (5282.8209ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (5243.9591ms)\n▶ AsyncContextFrame (5837.2145ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 5853.3979\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-enable-disable.js (4932.6085ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enable-disable.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 4)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":6372.079,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}},{"testName":"parallel/test-runner-watch-mode-complex","timestamp":1725479841258,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 3,win10-COMPILED_BY-vs2022 #29948","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022/29948/","buildNumber":29948,"builtOn":"test-azure_msft-win10_vs2019-x64-1","nodeVersion":"23.0.0","commitHash":"26610546771c67ea3c0427bd8df7e394da2960d0","callStack":[{"upstreamBuild":65512,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":73936,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":61933,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54651"}],"tap":{"ok":false,"name":"parallel/test-runner-watch-mode-complex","id":686,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ test runner watch mode with more complex setup\n  ✖ should run tests when a dependency changed after a watched test file being deleted (6293.0182ms)\n    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 2/. Input:\n    \n    '✔ second test has ran (18.5396ms)\\n' +\n      '✔ first test has ran (18.9061ms)\\n' +\n      '✔ second test has ran (10.4508ms)\\n' +\n      'ℹ tests 3\\n' +\n      'ℹ suites 0\\n' +\n      'ℹ pass 3\\n' +\n      'ℹ fail 0\\n' +\n      'ℹ cancelled 0\\n' +\n      'ℹ skipped 0\\n' +\n      'ℹ todo 0\\n' +\n      'ℹ duration_ms 2166.3498\\n'\n    \n        at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-watch-mode-complex.mjs:99:12)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 0)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: true,\n      code: 'ERR_ASSERTION',\n      actual: '✔ second test has ran (18.5396ms)\\n✔ first test has ran (18.9061ms)\\n✔ second test has ran (10.4508ms)\\nℹ tests 3\\nℹ suites 0\\nℹ pass 3\\nℹ fail 0\\nℹ cancelled 0\\nℹ skipped 0\\nℹ todo 0\\n...',\n      expected: /tests 2/,\n      operator: 'match'\n    }\n\n▶ test runner watch mode with more complex setup (6340.1196ms)\nℹ tests 1\nℹ suites 1\nℹ pass 0\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 6462.4952\n\n✖ failing tests:\n\ntest at test\\parallel\\test-runner-watch-mode-complex.mjs:53:3\n✖ should run tests when a dependency changed after a watched test file being deleted (6293.0182ms)\n  AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 2/. Input:\n  \n  '✔ second test has ran (18.5396ms)\\n' +\n    '✔ first test has ran (18.9061ms)\\n' +\n    '✔ second test has ran (10.4508ms)\\n' +\n    'ℹ tests 3\\n' +\n    'ℹ suites 0\\n' +\n    'ℹ pass 3\\n' +\n    'ℹ fail 0\\n' +\n    'ℹ cancelled 0\\n' +\n    'ℹ skipped 0\\n' +\n    'ℹ todo 0\\n' +\n    'ℹ duration_ms 2166.3498\\n'\n  \n      at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-watch-mode-complex.mjs:99:12)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 0)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: true,\n    code: 'ERR_ASSERTION',\n    actual: '✔ second test has ran (18.5396ms)\\n✔ first test has ran (18.9061ms)\\n✔ second test has ran (10.4508ms)\\nℹ tests 3\\nℹ suites 0\\nℹ pass 3\\nℹ fail 0\\nℹ cancelled 0\\nℹ skipped 0\\nℹ todo 0\\n...',\n    expected: /tests 2/,\n    operator: 'match'\n  }"},"time":8106.031,"fullname":"parallel/test-runner-watch-mode-complex","closingTestPoint":false}}]}