{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1725752394310,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #30077","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30077/","buildNumber":30077,"builtOn":"test-rackspace-win2019_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"0a04ffbeff873560d05c6f79ec16ce2465066349","callStack":[{"upstreamBuild":65669,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74134,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62120,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54434"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":109,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (5539.5992ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (5257.9462ms)\n  ✖ async-hooks\\test-async-local-storage-async-functions.js (5876.8195ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-functions.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 2)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-dgram.js (5937.1509ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (5917.3032ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (5526.4667ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (6336.8868ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (5314.9945ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (5765.2528ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (6104.6836ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (5580.8957ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (5342.8179ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (5960.811ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (5675.4156ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (5720.8604ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (5357.9978ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (5907.2093ms)\n  ✔ parallel\\test-async-local-storage-bind.js (5318.4059ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (5698.5634ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (5626.656ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (5191.8251ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (5946.0326ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (5421.112ms)\n▶ AsyncContextFrame (6801.4967ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 6834.9893\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-async-functions.js (5876.8195ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-functions.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 2)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":7436.709,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}