{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1726650532363,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #30333","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/30333/","buildNumber":30333,"builtOn":"test-rackspace-win2022_vs2022-x64-3","nodeVersion":"23.0.0","commitHash":"c64f32ea23ae7814c2e5ed21707f3494b80ffe0b","callStack":[{"upstreamBuild":66013,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74537,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62518,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54529"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":448,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1518.2331ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (1575.7615ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1865.9795ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (1588.2536ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1254.1597ms)\n  ✖ async-hooks\\test-async-local-storage-enter-with.js (1630.0122ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:931:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-errors.js (1951.1422ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1284.4698ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1601.8406ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1358.3878ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1308.2648ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1450.805ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1605.9571ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1197.354ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1239.6671ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1161.7244ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1354.1294ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1161.9656ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1197.9501ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1226.3667ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1176.3999ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1494.5677ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1186.0417ms)\n▶ AsyncContextFrame (32410.2411ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 32426.4456\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-enter-with.js (1630.0122ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:931:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":32972.242,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}