{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1727043158292,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #30454","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/30454/","buildNumber":30454,"builtOn":"test-rackspace-win2022_vs2022-x64-2","nodeVersion":"23.0.0","commitHash":"2b86de92f128699e4aff47da88a765b791e324c7","callStack":[{"upstreamBuild":66145,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74710,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62676,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"55039"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":431,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1434.5421ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (1558.6476ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1593.7943ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (1562.5752ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1499.0904ms)\n  ✖ async-hooks\\test-async-local-storage-enter-with.js (1245.7426ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:932:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:630:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-errors.js (1279.9406ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1297.1254ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1347.2119ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1226.187ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1241.2582ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1236.2699ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1619.0359ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1073.4948ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1150.3989ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1040.3808ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1237.3783ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1110.9825ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1071.8826ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1050.5955ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1064.8935ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1410.8093ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1100.5273ms)\n✖ AsyncContextFrame (29469.143ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 29483.1483\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-enter-with.js (1245.7426ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:932:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:630:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":29900.463,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}