{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1727730704751,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #30618","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30618/","buildNumber":30618,"builtOn":"test-rackspace-win2019_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"9c584e11be8f02b861129810e40df50be9e24915","callStack":[{"upstreamBuild":66314,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74923,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62863,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"53848"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":442,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1617.7201ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (2035.2512ms)\n  ✖ async-hooks\\test-async-local-storage-async-functions.js (2178.0442ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-functions.js failed with exit code 3221225477\n    \n    3221225477 !== 0\n    \n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:935:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-dgram.js (2151.4441ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1738.6777ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (1913.6058ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (1914.7215ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1642.6596ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1921.1216ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1636.1823ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1396.4314ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1470.9699ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1713.0627ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1303.6659ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1209.2706ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1203.0404ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1464.2098ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1329.9007ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1310.7092ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1287.5332ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1298.579ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1576.8841ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1261.2751ms)\n✖ AsyncContextFrame (36594.247ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 36610.2112\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-async-functions.js (2178.0442ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-functions.js failed with exit code 3221225477\n  \n  3221225477 !== 0\n  \n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:935:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":37125.415,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}