{"failedTests":[{"testName":"parallel/test-runner-coverage","timestamp":1731757362141,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 1,win11-arm64-COMPILED_BY-vs2022-arm64 #31270","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/31270/","buildNumber":31270,"builtOn":"test-azure_msft-win11_vs2022-arm64-3","nodeVersion":"24.0.0","commitHash":"34817548cc73f717eda0d82eb476e35a9a79cb31","callStack":[{"upstreamBuild":66989,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":75817,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":63570,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"52888"}],"tap":{"ok":false,"name":"parallel/test-runner-coverage","id":766,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ test coverage report\n  ✔ handles the inspector not being available (2.2781ms)\n✔ test coverage report (4.0595ms)\n▶ test tap coverage reporter\n  ✔ coverage is reported and dumped to NODE_V8_COVERAGE if present (392.8892ms)\n  ✔ coverage is reported without NODE_V8_COVERAGE present (530.0549ms)\n✔ test tap coverage reporter (923.5558ms)\n▶ test spec coverage reporter\n  ✔ coverage is reported and dumped to NODE_V8_COVERAGE if present (1116.3236ms)\n  ✔ coverage is reported without NODE_V8_COVERAGE present (597.3298ms)\n✔ test spec coverage reporter (1714.2657ms)\n✖ single process coverage is the same with --test (625.2234ms)\n  AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n  \n    assert(!findCoverageFileForPid(result.pid))\n  \n      at TestContext.<anonymous> (d:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\parallel\\test-runner-coverage.js:161:3)\n      at Test.runInAsyncScope (node:async_hooks:211:14)\n      at Test.run (node:internal/test_runner/test:934:25)\n      at Test.processPendingSubtests (node:internal/test_runner/test:633:18)\n      at Test.postRun (node:internal/test_runner/test:1045:19)\n      at Test.run (node:internal/test_runner/test:973:12)\n      at async Test.processPendingSubtests (node:internal/test_runner/test:633:7) {\n    generatedMessage: true,\n    code: 'ERR_ASSERTION',\n    actual: false,\n    expected: true,\n    operator: '=='\n  }\n\n✔ coverage is combined for multiple processes (685.4772ms)\n﹣ coverage works with isolation=none (0.4255ms) # SKIP\n▶ coverage reports on lines, functions, and branches\n  ✔ does not include node_modules (0.3729ms)\n  ✔ reports on function coverage (0.261ms)\n  ✔ reports on branch coverage (0.2831ms)\n  ✔ reports on line coverage (0.2955ms)\n✔ coverage reports on lines, functions, and branches (638.6122ms)\n✔ coverage with ESM hook - source irrelevant (868.1993ms)\n✔ coverage with ESM hook - source transpiled (851.3147ms)\n✔ coverage with excluded files (533.558ms)\n✔ coverage with included files (426.3934ms)\n✔ coverage with included and excluded files (506.0434ms)\n✔ correctly prints the coverage report of files contained in parent directories (709.3748ms)\nℹ tests 22\nℹ suites 0\nℹ pass 20\nℹ fail 1\nℹ cancelled 0\nℹ skipped 1\nℹ todo 0\nℹ duration_ms 8507.8813\n\n✖ failing tests:\n\ntest at test\\parallel\\test-runner-coverage.js:150:1\n✖ single process coverage is the same with --test (625.2234ms)\n  AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n  \n    assert(!findCoverageFileForPid(result.pid))\n  \n      at TestContext.<anonymous> (d:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\parallel\\test-runner-coverage.js:161:3)\n      at Test.runInAsyncScope (node:async_hooks:211:14)\n      at Test.run (node:internal/test_runner/test:934:25)\n      at Test.processPendingSubtests (node:internal/test_runner/test:633:18)\n      at Test.postRun (node:internal/test_runner/test:1045:19)\n      at Test.run (node:internal/test_runner/test:973:12)\n      at async Test.processPendingSubtests (node:internal/test_runner/test:633:7) {\n    generatedMessage: true,\n    code: 'ERR_ASSERTION',\n    actual: false,\n    expected: true,\n    operator: '=='\n  }"},"time":8976.957,"fullname":"parallel/test-runner-coverage","closingTestPoint":false}}]}